# Generated by Django 5.2.7 on 2025-10-04 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Horário de Início')),
                ('end_time', models.TimeField(verbose_name='Horário de Término')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('CONFIRMED', 'Confirmado'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado'), ('NO_SHOW', 'Não Compareceu')], default='SCHEDULED', max_length=15, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('price_charged', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado')),
                ('confirmation_sent', models.BooleanField(default=False, verbose_name='Confirmação Enviada')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Lembrete Enviado')),
                ('barber', models.ForeignKey(limit_choices_to={'role': 'BARBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_barber', to=settings.AUTH_USER_MODEL, verbose_name='Barbeiro')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
