# Generated by Django 5.2.7 on 2025-10-04 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('role', models.CharField(choices=[('CLIENT', 'Cliente'), ('BARBER', 'Barbeiro'), ('OWNER', 'Dono')], default='CLIENT', max_length=10, verbose_name='Tipo de Usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('receive_email_notifications', models.BooleanField(default=True, verbose_name='Receber notificações por e-mail')),
                ('receive_sms_notifications', models.BooleanField(default=False, verbose_name='Receber notificações por SMS')),
                ('receive_whatsapp_notifications', models.BooleanField(default=False, verbose_name='Receber notificações por WhatsApp')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarberScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Horário Inicial')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Horário Final')),
                ('all_day', models.BooleanField(default=False, verbose_name='Dia Inteiro')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('barber', models.ForeignKey(limit_choices_to={'role': 'BARBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Barbeiro')),
            ],
            options={
                'verbose_name': 'Bloqueio de Agenda',
                'verbose_name_plural': 'Bloqueios de Agenda',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
